FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY HelloWorldFinal/*.csproj ./HelloWorldFinal/
COPY Services/*.csproj ./Services/
WORKDIR /app/HelloWorldFinal
RUN dotnet restore

# copy and build app and libraries
WORKDIR /app/
COPY HelloWorldFinal/. ./HelloWorldFinal/
COPY Services/. ./Services/
WORKDIR /app/HelloWorldFinal
RUN dotnet publish -c Release -r linux-arm -o out --self-contained true /p:PublishTrimmed=true


FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-buster-slim-arm32v7 AS runtime
WORKDIR /app
COPY --from=build /app/HelloWorldFinal/out ./
ENTRYPOINT ["./HelloWorldFinal"]